package constants

//TracifiedBackend The URL TO Traceability Staging
// var TracifiedBackend="https://staging.api.tracified.com"
//TracifiedBackend The URL TO Traceability Production
var TracifiedBackend = "https://api.tracified.com"

//  var TracifiedBackend="http://localhost:3001"

//RawTDP The Route to Get Raw TDP Data
var RawTDP = "/api/v2/dataPackets/raw?id="

//BackendToken The Token used to Retrieve Raw TDP from Traceability DataStore
//Will Expire in 03/19/2022 @ 12:31pm (UTC).
var BackendToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJjb21wYW55IjoiOTl4IFRlY2hub2xvZ3kiLCJ1c2VySUQiOiI4NTllYzZjMC0xODAxLTExZTktODViNC0zZmRjYTAyOWYwY2MiLCJ1c2VybmFtZSI6InZpbnVzaGFwQDk5eC5sayIsImxvY2FsZSI6IlNyaSBMYW5rYSIsInBlcm1pc3Npb25zIjp7IjAiOlsiNyIsIjgiLCI5Il0sIjAwMjAxIjpbIjEiLCIyIiwiMyIsIjQiLCI1IiwiNiJdLCIwMDIwMiI6WyIxIiwiMiIsIjMiLCI0IiwiNSIsIjYiXSwiMDAyMDMiOlsiMSIsIjIiLCIzIiwiNCIsIjUiLCI2Il0sIjAwMjA0IjpbIjEiLCIyIiwiMyIsIjQiLCI1IiwiNiJdLCIwMDIwNSI6WyIxIiwiMiIsIjMiLCI0IiwiNSIsIjYiXSwiMDAyMDYiOlsiMSIsIjIiLCIzIiwiNCIsIjUiLCI2Il0sIjAwMjA3IjpbIjIiLCIzIiwiMSIsIjQiLCI1IiwiNiJdLCIwMDIwOCI6WyIxIiwiMiIsIjMiLCI0IiwiNSIsIjYiXSwiMDAyMDkiOlsiMSIsIjIiLCIzIiwiNCIsIjUiLCI2Il19LCJ0eXBlIjoiRmVpbGRPZmZpY2VyIiwidGVuYW50SUQiOiJkODdjNGYzMC0wOWE1LTExZTktOTgxZS0yNzI2ZjMwNWJiMjMiLCJhdXRoX3RpbWUiOjE1NDc1MjAyOTAsIm5hbWUiOiJWaW51c2hhIFBlcmVyYSIsInN0YWdlcyI6WyIwMDIwMSIsIjAwMjAyIiwiMDAyMDMiLCIwMDIwMyIsIjAwMjA0IiwiMDAyMDUiLCIwMDIwNiIsIjAwMjA3IiwiMDAyMDgiLCIwMDIwOSJdLCJwaG9uZV9udW1iZXIiOiIrOTQ3MTE4NDA2NzkiLCJlbWFpbCI6InZpbnVzaGFwQDk5eC5sayIsImFkZHJlc3MiOnsiZm9ybWF0dGVkIjoibm9uZSJ9LCJkb21haW4iOiJBZ3JpY3VsdHVyZSIsImRpc3BsYXlJbWFnZSI6Im5vbmUiLCJhY2Nlc3NUb2tlbiI6InBlbmRpbmciLCJpYXQiOjE1NDc1MjAyOTAsImV4cCI6MTY0NzY5MzA5MH0.aZgjFUlT9tR6Qh5cL9ZLuTbeFiykQSpNia1dhFOU0fk"
