---
- hosts: production
  environment:
    PYTHONPATH: /home/{{ ansible_user }}/.local/lib/python2.7/site-packages
  tasks:
    - name: Add docker gpg key
      become: true
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Check if docker repository is present
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
    - name: Install docker CE
      become: true
      apt:
        name: docker-ce
        state: present
        update_cache: yes
    - name: Install pip
      become: true
      apt:
        name: python-pip
        state: present
        update_cache: yes
    - name: Install docker-py
      pip:
        name: docker
    - name: Install AWS CLI
      pip:
        name: awscli
    - name: Log into docker registry and force re-authorization
      become: true
      docker_login:
        registry: registry.tracified.com
        username: "{{ lookup('env', 'DOCKER_USER') }}"
        password: "{{ lookup('env', 'DOCKER_PASS') }}"
        reauthorize: yes
    - name: Create volume for docker
      become: true
      docker_volume:
        name: gateway_logs
    - name: Run docker
      become: true
      debugger: on_failed
      docker_container:
        name: tracified-gateway
        image: registry.tracified.com/tracified/gateway-prod
        published_ports: "8000:8000"
        restart: yes
        restart_policy: on-failure
        state: started
        pull: yes
        volumes:
          - gateway_logs:/app/logs
        env:
          GATEWAY_PORT: "{{ lookup('env','GATEWAY_PORT') }}"
          PublicKey: "{{ lookup('env','PublicKey') }}"
          SecretKey: "{{ lookup('env','SecretKey') }}"
          ENVIRONMENT: "{{ lookup('env','ENVIRONMENT') }}"
          DB_URI: "{{ lookup('env','DB_URI') }}"
          DB_NAME: "{{ lookup('env','DB_NAME') }}"
          ADMIN_BE_MONGODB_URI: "{{ lookup('env','ADMIN_BE_MONGODB_URI') }}"
          ADMIN_BE_DB_NAME: "{{ lookup('env','ADMIN_BE_DB_NAME') }}"
          RABBITMQ_SERVER_URI: "{{ lookup('env','RABBITMQ_SERVER_URI') }}"
          HORIZONCLIENT: "{{ lookup('env','HORIZONCLIENT') }}"
          SOLANACLIENT: "{{ lookup('env','SOLANACLIENT') }}"
          STELLARLABORATORYCLIENT: "{{ lookup('env','STELLARLABORATORYCLIENT') }}"
          TRACIFIEDBACKEND: "{{ lookup('env','TRACIFIEDBACKEND') }}"
          TRACIFIEDBACKENDTOKEN: "{{ lookup('env','TRACIFIEDBACKENDTOKEN') }}"
          AWS_ACCESS_KEY: "{{ lookup('env','AWS_ACCESS_KEY') }}"
          AWS_SECRET_KEY: "{{ lookup('env','AWS_SECRET_KEY') }}"
          AWS_REGION: "{{ lookup('env','AWS_REGION') }}"
          AWS_KMS_KEY_ID: "{{ lookup('env','AWS_KMS_KEY_ID') }}"
          NFTSTELLARISSUERPUBLICKEYK: "{{ lookup('env','NFTSTELLARISSUERPUBLICKEYK ') }}"
          NFTSTELLARISSUERSECRETKEY: "{{ lookup('env','NFTSTELLARISSUERSECRETKEY ') }}"
          NFTAccountKeyEncodedPassword: "{{ lookup('env','NFTAccountKeyEncodedPassword') }}"
          NFTISSUESECRETKEYPOLYGON: "{{ lookup('env','NFTISSUESECRETKEYPOLYGON') }}"
          NFTISSUEPUBLICKKEYPOLYGON: "{{ lookup('env','NFTISSUEPUBLICKKEYPOLYGON') }}"
          NFTRECEIVERPUBLICKPOLYGON: "{{ lookup('env','NFTRECEIVERPUBLICKPOLYGON') }}"
          NFTRECEIVERSECRETKEYPOLYGON: "{{ lookup('env','NFTRECEIVERSECRETKEYPOLYGON') }}"
          HOMEDOMAIN: "{{ lookup('env','HOMEDOMAIN') }}"
          SPONSORERPK: "{{ lookup('env','SPONSORERPK') }}"
          SPONSORERSK: "{{ lookup('env','SPONSORERSK') }}"
          WALLETSECRET: "{{ lookup('env','WALLETSECRET') }}"
          GMAILHOST: "{{ lookup('env','GMAILHOST') }}"
          GOMAILPORT: "{{ lookup('env','GOMAILPORT') }}"
          GOMAILSENDER: "{{ lookup('env','GOMAILSENDER') }}"
          GOMAILSENDERPW: "{{ lookup('env','GOMAILSENDERPW') }}"
          ALLOWREQUESTPERDAY: "{{ lookup('env','ALLOWREQUESTPERDAY') }}"
          ALLOWREQUESTPERWEEK: "{{ lookup('env','ALLOWREQUESTPERWEEK') }}"
          SOCILAIMPACTPUBLICKKEY: "{{ lookup('env','SOCILAIMPACTPUBLICKKEY') }}"
          SOCILAIMPACTSEED: "{{ lookup('env','SOCILAIMPACTSEED') }}"
          RABBITUSER: "{{ lookup('env','RABBITUSER') }}"
          RABBITPASSWORD: "{{ lookup('env','RABBITPASSWORD') }}"
          RABBITMQ_SERVICE_HOST: "{{ lookup('env','RABBITMQ_SERVICE_HOST') }}"
          RABBITPORT: "{{ lookup('env','RABBITPORT') }}"
          LOGSTYPE: "{{ lookup('env','LOGSTYPE') }}"
          QUEUE_FLAG: "{{ lookup('env','QUEUE_FLAG') }}"
          TRACIFIED_ADMIN: "{{ lookup('env','TRACIFIED_ADMIN') }}"
          NFTQUEUE_NAME: "{{ lookup('env','NFTQUEUE_NAME') }}"
          FONEW_FLAG: "{{ lookup('env','FONEW_FLAG') }}"
          CACHE_CONNECTION: "{{ lookup('env','CACHE_CONNECTION') }}"
          JWT_DECODE_KEY: "{{ lookup('env','JWT_DECODE_KEY') }}"
          STELLAR_KEY_LOW_BALANCE_BUFFER_AMOUNT : "{{ lookup('env','STELLAR_KEY_LOW_BALANCE_BUFFER_AMOUNT') }}"
          STELLAR_BASE_RESERVE : "{{ lookup('env','STELLAR_BASE_RESERVE') }}"
